FROM golang:1.23.1-alpine3.20 AS builder

WORKDIR /app
COPY . /app/
RUN apk update && apk add --no-cache ca-certificates && update-ca-certificates

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/socket ./cmd/socket/ 

FROM scratch AS runner

COPY --from=builder  /bin/socket /app/
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENTRYPOINT ["/app/socket"]
